controllers:
    resource: ../src/Controller/
    type: annotation

# config/routes.yaml
test:
    path: /test
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\TestController::Response

user_login:
    path: /login
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\LoginController::Response

user_register:
    path: /register
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\RegisterController::Response
    

kernel:
    resource: ../src/Kernel.php
    type: annotation
